#!/bin/bash
pgrep -f "nsxiv -b "$WALLPAPERS" -rot" && exit 1
notify-send "\"Q\" to choose wallpaper"
wallpaper="$(nsxiv -b "$WALLPAPERS" -rot)"
if [[ $wallpaper ]] then
	killall swaybg
	wal -i "$wallpaper" -n
	waybar-background &
	dunst-theme &
	swaybg -i "$wallpaper" -m fill
fi
