#!/bin/bash
pgrep -f "nsxiv -b "$WALLPAPERS" -rot" && exit 1
notify-send "Press \"Q\" to set the wallpaper"
wallpaper="$(nsxiv -b "$WALLPAPERS" -rot)"
WALLPAPER_PATH="$HOME/.cache/wallpaper"
if [[ -f $wallpaper ]] then
	ln -s "$wallpaper" "$WALLPAPER_PATH" -f
	swaymsg reload
fi
