#!/bin/sh
wallpaper="$(fd . ${WALLPAPERS} -t file | wofi -d -r "echo \"%s\" | sed 's/.*\///g'")"
if [[ $wallpaper ]] then
    killall swaybg
    wal -i "$wallpaper" -n
    waybarBackground &
    dunstTheme &
    killall waybar && waybar &
    swaybg -i "$wallpaper" -m fill
fi
