#!/bin/sh
# Q for setting the wallpaper
wallpaper="$(nsxiv "$WALLPAPERS" -rot)"
if [[ $wallpaper ]] then
    killall swaybg
    wal -i "$wallpaper" -n
    waybarBackground &
    dunstTheme &
    killall waybar && waybar &
    swaybg -i "$wallpaper" -m fill
fi
