#!/bin/sh
curl -s "https://archlinux.org/mirrorlist/?country=IN&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - | sudo tee -a /etc/pacman.d/mirrorlist > /dev/null
sudo pacman -Syyu
