#!/bin/bash

# Load music
music_directories="$(find -L "${MUSIC_DIR}" -type d)"

declare playlist

choice="$(echo -e "$music_directories" | wofi -id -r "echo -n \"%s\" | sed 's/\/$//;s/.*\///g'")"
[ ! -d "$choice" ] && exit 1

sort_method=$(echo -e "Date\nShuffle" | wofi -id --width 100 --height 115 -p "Order By") 

case "$sort_method" in
  Date) playlist="$(find -L "$choice" -type f '(' -name '*.mp3' -o -name '*.flac' -o -name '*.wav' ')' -print0 | xargs -0 ls -t)";;
  Shuffle) playlist="$(find -L "$choice" -type f '(' -name '*.mp3' -o -name '*.flac' -o -name '*.wav' ')' | shuf)";;
  *) exit 1 ;;
esac 

mpv_running="$(pgrep -f "mpv.*")"

if [ "$mpv_running" ];then

  notify-send "Another instance of mpv is already running"
  action="$(echo -e "Yes\nNo" | wofi -id --width 100 --height 115 -p "Kill mpv ?")"

  case "$action" in
    Yes) pkill -f "mpv.*";;
    No) :;;
    *) exit 1;;
  esac

fi

echo "$playlist" | xargs -d '\n' mpv
