#!/bin/bash
selected="$( echo -e "  Poweroff\n  Reboot\n  Suspend\n  Lock\n  Hibernate" \
	| wofi -i --dmenu --width 200 --height 160 -s ~/.config/wofi/powermenu.css )"
selected="${selected##* }"
case "$selected" in
"Hibernate") 
	swaylock -c 000000 &
	systemctl hibernate
	;;
"Lock") 
	swaylock -c 000000 
	;;
"Poweroff") 
	systemctl poweroff
	;;
"Reboot") 
	systemctl reboot
	;;
"Suspend") 
	swaylock -c 000000 &
	systemctl suspend
	;;
esac
