#!/bin/bash
selected=$(nmcli -t -f active,name connection | wofi --style ~/.config/wofi/wofi-dmenu.css -id -r "printf '%s' | sed 's/yes\:/*/;s/no\://'")
connection="${selected#*:}"
[ "$selected" ] || exit 1
[ "${selected%%:*}" = "no" ] && nmcli connection up "$connection" || nmcli connection down "$connection"
