#!/bin/sh
selected=$(nmcli -t -f active,name connection | wofi -d -r "echo -n \"%s\" | sed 's/yes\:/*/;s/no\://'")
connection="${selected#*:}"
[ "$selected" ] || exit 1
[ "${selected%%:*}" = "no" ] && nmcli connection up "$connection" || nmcli connection down "$connection" 
